In [7]:
import numpy as np
#Найти индексы ненулевых элементов в заданном массиве.
array = np.array([0, 5, 0, 10, 0, 15])
nonzero_indices = np.nonzero(array)

print(*nonzero_indices)

[1 3 5]


In [8]:
import numpy as np
#Создать nxn единичную матрицу.
n = 4  # Задаем размерность матрицы (4 x 4)
identity_matrix = np.eye(n)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
import numpy as np
#Создать массив nxnxn со случайными значениями
n = 3  # Задаем размерность массива (3 x 3 x 3)
random_array = np.random.random((n, n, n))

print(random_array)


[[[0.11896129 0.83722607 0.4827251 ]
  [0.6399285  0.25691661 0.84141418]
  [0.1120742  0.45758966 0.20642585]]

 [[0.92557716 0.02603765 0.13078645]
  [0.56920338 0.86364981 0.90525726]
  [0.64089575 0.45155    0.22337082]]

 [[0.3767538  0.06075197 0.57682645]
  [0.61338864 0.30975269 0.49259834]
  [0.14114534 0.22120174 0.95650894]]]


In [9]:
import numpy as np
#Создать вектор (одномерный массив) размера n, заполненный нулями
n = 5  # Задаем размерность вектора (размерность = 5)
zero_vector = np.zeros(n)

print(zero_vector)


[0. 0. 0. 0. 0.]


In [10]:
import numpy as np
#Создать вектор размера 1n, заполненный нулями, но пятый элемент равен 1
n = 10  # Задаем размер вектора (размер = 10)
zero_vector = np.zeros(n)
zero_vector[4] = 1  # Присваиваем значение 1 пятому элементу вектора

print(zero_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
import numpy as np
#Создать вектор со значениями от n до m
n = 1  # Начальное значение
m = 10  # Конечное значение (включительно)
vector = np.arange(n, m+1)

print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
import numpy as np
#Развернуть одномерный массив (первый становится последним)
array = [1, 2, 3, 4, 5]  # Одномерный массив
reversed_array = array[::-1]

print(reversed_array)


[5, 4, 3, 2, 1]


In [13]:
import numpy as np
#Создать матрицу с 0 внутри, и 1 на границах
n = 5  # Задаем размерность матрицы (n x n)

# Создание матрицы, заполненной единицами
matrix = np.ones((n, n))

# Замена внутренних значений на нули
matrix[1:-1, 1:-1] = 0

print(matrix)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
import numpy as np
#Создать nxn матрицу и заполнить её в шахматном порядке
n = 4  # Задаем размерность матрицы (4x4)

# Создание матрицы, заполненной нулями
matrix = np.zeros((n, n))

# Заполнение шахматного узора (чередование 0 и 1)
matrix[::2, ::2] = 0
matrix[1::2, 1::2] = 0
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [28]:
import numpy as np
#Заменить максимальный элемент на ноль
array = np.array([1, 2, 3, 4, 5])  # Массив

max_index = np.argmax(array)  # Индекс максимального элемента
array[max_index] = 0  # Замена максимального элемента на ноль

print(array)


[1 2 3 4 0]


In [27]:
import numpy as np
#Найти ближайшее к заданному значению число в заданном массиве
array = np.array([1, 3, 5, 7, 9])  # Заданный массив
value = 6  # Заданное значение

diff = np.abs(array - value)  # Вычисление абсолютных значений разности
closest_index = np.argmin(diff)  # Нахождение индекса элемента с минимальной разностью
closest_value = array[closest_index]  # Получение ближайшего значения

print(closest_value)



5


In [26]:
import numpy as np
#Дан четырехмерный массив, посчитать сумму по последним двум осям
# Создание четырехмерного массива
array = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                  [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# Расчет суммы по последним двум осям
sum_last_two_axes = np.sum(array, axis=(2, 3))

print(sum_last_two_axes)


[[10 26]
 [42 58]]


In [10]:
import numpy as np
#Определить, есть ли в двумерном массиве нулевые столбцы
# Создание двумерного массива
array = np.array([[1, 0, 3],
                  [0, 0, 0],
                  [4, 0, 6]])

# Проверка наличия нулевых столбцов
zero_columns = np.any(array == 0, axis=0)

if np.any(zero_columns):
    print("В массиве есть нулевые столбцы.")
else:
    print("В массиве нет нулевых столбцов.")


В массиве есть нулевые столбцы.


In [24]:
import numpy as np
#	Отнять среднее из каждой строки в матрице
# Создание матрицы
matrix = np.array([[1, 3, 5],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисление среднего значения каждой строки
mean_row = np.mean(matrix, axis=1, keepdims=True)
print(mean_row)
# Отнимание среднего значения из каждой строки
result_matrix = matrix - mean_row

print(result_matrix)



[[3.]
 [5.]
 [8.]]
[[-2.  0.  2.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [21]:
import numpy as np
# Создайте вектор с элементами от 10 до 50
vector = np.arange(10, 51, 1)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
import numpy as np

matrix = np.arange(0, 25).reshape(5, 5) % 7
print(matrix)


[[0 1 2 3 4]
 [5 6 0 1 2]
 [3 4 5 6 0]
 [1 2 3 4 5]
 [6 0 1 2 3]]


In [20]:
import numpy as np
#Умножьте матрицу размерности (5, 3) на (3, 2)
# Создание матрицы размерности (5, 3)
matrix1 = np.random.randint(0, 10, size=(5, 3))
print(matrix1)
# Создание матрицы размерности (3, 2)
matrix2 = np.random.randint(0, 10, size=(3, 2))
print(matrix2)
# Умножение матриц
result = np.matmul(matrix1, matrix2)

print(result)


[[0 7 4]
 [6 0 2]
 [5 9 3]
 [3 7 1]
 [4 8 3]]
[[5 3]
 [6 0]
 [4 6]]
[[58 24]
 [38 30]
 [91 33]
 [61 15]
 [80 30]]


In [16]:
import numpy as np

# Создание матрицы (10, 10) и заполнение ее значениями 1
matrix = np.zeros((10, 10))

# Заполнение границ матрицы значениями 0
matrix[1:-1, 1:-1] = 1

print(matrix)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:

vector = [10, 15, 20, 25, 30]
number = 22

nearest_element = min(vector, key=lambda x: abs(x - number))
print(nearest_element)





In [6]:
import numpy as np

# Создаем трехмерный массив размера (height, width, numChannels) со случайными значениями
height, width, numChannels = 200, 300, 3
image = np.random.randint(0, 256, size=(height, width, numChannels))

# Вектор коэффициентов
coefficients = np.array([0.299, 0.587, 0.114])

# Умножаем трехмерный массив на вектор коэффициентов
gray_image = np.dot(image, coefficients)

# Выводим результат
print(gray_image)


[[164.876  51.533 164.89  ... 102.52  144.693 108.359]
 [ 81.935 173.866 144.224 ...  94.753 162.575 193.71 ]
 [137.842  63.724 193.93  ...  41.198  84.518 102.726]
 ...
 [121.916  85.467  52.457 ...  92.099 117.672 124.158]
 [134.776 187.801 139.085 ...  90.466 156.515 168.232]
 [ 99.19  112.258 128.292 ... 219.258  46.344 161.29 ]]
